target 'SwiftEntryKitDemo' do
    platform :ios, '9.0'
    use_frameworks!
    pod 'BinartSwiftFeedback', :path => '../'
end

target 'SwiftEntryKitTests' do
    platform :ios, '9.0'
    use_frameworks!
    pod 'BinartSwiftFeedback', :path => '../'
    pod 'Quick', '2.0.0'
    pod 'Nimble', '8.0.1'
end
